services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    command: npm run dev
  incidentReport:
    build:
      context: ./incidentReport
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./incidentReport:/app
    command: npm run start
